service: tweetSkill

frameworkVersion: ">=1.0.0 <2.0.0"
#frameworkVersion: "=1.0.3"
provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  stage: develop
  region: eu-west-1

environment:
  TW_CONSUMER_KEY: ""
  TW_CONSUMET_SECRET: ""
  TW_ACESS_TOKEN_KEY: ""
  TW_ACCESS_TOKEN_SECRET: ""
  ALEXA_APP_ID: ""


functions:
  sendTweet:
    handler: handler.sendTweet
    events:
      - alexaSkill

plugins:
  - serverless-local-alexa-server
  #nodemon --exec "serverless local-alexa-server --port 8080" -e "js yml json"