service: tweetSkill

frameworkVersion: ">=1.0.0 <2.0.0"
#frameworkVersion: "=1.0.3"
provider:
  #name: aws
  #runtime: nodejs:default
  #runtime: nodejs6.10
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  stage: develop
  region: eu-west-1

functions:
  sendTweet:
    handler: handler.sendTweet
    events:
      - alexaSkill

plugins:
  - serverless-local-alexa-server
  #nodemon --exec "serverless local-alexa-server --port 8080" -e "js yml json"